<?php
/**
 * Plugin Name:  GatherPress Cache Invalidation Hooks
 * Plugin URI:   
 * Description:  Cache Invalidation system based on event end dates, similar to WordPress scheduled posts, but for GatherPress.
 * Author:       carstenbach & WordPress Telex
 * Author URI:   
 * Version:      0.1.0
 * Requires PHP: 7.4
 * Requires Plugins:  gatherpress
 * Text Domain:  gatherpress-cache-invalidation-hooks
 * Domain Path:  /languages
 * License:      GNU General Public License v2.0 or later
 * License URI:  https://www.gnu.org/licenses/gpl-2.0.html
 *
 * @package GatherPress\Cache_Invalidation_Hooks
 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit; // @codeCoverageIgnore

// Constants.
define( 'GATHERPRESS_CACHE_INVALIDATION_HOOKS_VERSION', current( get_file_data( __FILE__, array( 'Version' ), 'plugin' ) ) );
define( 'GATHERPRESS_CACHE_INVALIDATION_HOOKS_CORE_PATH', __DIR__ );

/**
 * Adds the GatherPress\Cache_Invalidation_Hooks namespace to the autoloader.
 *
 * This function hooks into the 'gatherpress_autoloader' filter and adds the
 * GatherPress\Cache_Invalidation_Hooks namespace to the list of namespaces with its core path.
 *
 * @param array<string, string> $namespaces An associative array of namespaces and their paths.
 * @return array<string, string> Modified array of namespaces and their paths.
 */
function gatherpress_cache_invalidation_hooks_autoloader( array $namespaces ): array {
	$namespaces['GatherPress_Cache_Invalidation_Hooks'] = GATHERPRESS_CACHE_INVALIDATION_HOOKS_CORE_PATH;

	return $namespaces;
}
add_filter( 'gatherpress_autoloader', 'gatherpress_cache_invalidation_hooks_autoloader' );

/**
 * Initializes the setup.
 *
 * This function hooks into the 'plugins_loaded' action to ensure that
 * the instances are created once all plugins are loaded,
 * only if the GatherPress plugin is active.
 *
 * @return void
 */
function gatherpress_cache_invalidation_hooks_setup(): void {
	if ( defined( 'GATHERPRESS_VERSION' ) ) {
		\GatherPress_Cache_Invalidation_Hooks\Cron_Scheduler::get_instance();
		\GatherPress_Cache_Invalidation_Hooks\Option_Tracker::get_instance();
	}
}
add_action( 'plugins_loaded', 'gatherpress_cache_invalidation_hooks_setup' );

/**
 * Plugin deactivation cleanup.
 *
 * Removes all scheduled wp-cron jobs, and the tracker option, when the plugin is deactivated.
 *
 * @since 0.1.0
 * @return void
 */
function gatherpress_cache_invalidation_hooks_deactivate(): void {
	$cron_scheduler = \GatherPress_Cache_Invalidation_Hooks\Cron_Scheduler::get_instance();
	$option_tracker = \GatherPress_Cache_Invalidation_Hooks\Option_Tracker::get_instance();

	if ( $option_tracker->is_tracker_enabled() ) {

		$upcoming_events = get_option( $option_tracker::OPTION_KEY );
	} else {

		$upcoming_events = new \WP_Query(
			array(
				'post_type'               => 'gatherpress_event',
				'post_status'             => 'publish',
				'gatherpress_event_query' => 'upcoming',
				'order'                   => 'desc',
				'posts_per_page'          => -1,
				'fields'                  => 'ids',
				'no_found_rows'           => false,
				'update_post_term_cache'  => false,
			)
		);
	}

	/**
	 * This is for sure an array of int or empty, because of 'fields' => 'ids'.
	 * 
	 * @var int[] $upcoming_events
	 */
	// Loop over upcoming events and remove all data (generated by this plugin).
	foreach ( $upcoming_events as $event_id ) {
		$cron_scheduler->clear_scheduled_cron( $event_id );
		$cron_scheduler->invalidate_caches( $event_id );
	}

	if ( $option_tracker->is_tracker_enabled() ) {
		// Find the timestamp of the next scheduled daily event.
		$timestamp = wp_next_scheduled( $option_tracker::CRON_HOOK );
		
		// If an event is scheduled, remove it.
		if ( is_int( $timestamp ) && $timestamp > 0 ) {
			wp_unschedule_event( $timestamp, $option_tracker::CRON_HOOK );
		}

		// Delete the tracking option.
		delete_option( $option_tracker::OPTION_KEY );
	}
}
register_deactivation_hook( __FILE__, 'gatherpress_cache_invalidation_hooks_deactivate' );
